spring:
  application:
    name: newsLetter
  data:
    mongodb:
      port: 27017
      host: localhost
      database: newsLetter
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Configuracao da porta do serviço de forma aleatoria
server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# RabbitMQ - Variaveis de ambiente customizadas
softwareHouse:
  rabbitmq:
    exchange: newsLetter.exchange
    rountingkey: newsLetter.employee.routingkey
    queue: newsLetter.queue

# Mostrar Queries MongoDB no Terminal:
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
